### ISSUE TITLE
`ext::sender` doesn't seem to return what implementation of `sender` on impl of External returns

### ISSUE THREAD

**Issue by snd** [paritytech/pwasm-test#9]
i've written a test that asserts that the initial supply is initially given to the contract creator:
https://gist.github.com/snd/2e49603e5e7a60881565e76dcc1452dd#file-test-rs-L8

it fails. not because of a bug in the contract. it seems because of a bug in pwasm-test.

when i run `cargo test --features=std -- --nocapture` i get the following output:

```
running 1 test
call to sender 141f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f
sender 0000000000000000000000000000000000000000
thread 'tests::should_initially_give_the_total_supply_to_the_creator' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `10000`', src/token.rs:192:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
test tests::should_initially_give_the_total_supply_to_the_creator ... FAILED

failures:

failures:
    tests::should_initially_give_the_total_supply_to_the_creator

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

i’ve implemented `sender` on `DummyExternal`:
to return a specific address (https://gist.github.com/snd/2e49603e5e7a60881565e76dcc1452dd#file-dummy_external-rs-L28).
i assumed that `ext::sender()` (https://gist.github.com/snd/2e49603e5e7a60881565e76dcc1452dd#file-token_contract-rs-L5)
would then return that address.

**it doesnt!**

`sender` returns `141f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f` but `ext::sender()`
returns `0000000000000000000000000000000000000000`.

**Comment by fckt** [comment]
here is the fix. Take a look https://github.com/paritytech/pwasm-test/pull/10

**Comment by snd** [comment]
https://github.com/paritytech/pwasm-test/pull/10 fixed this. thanks @fckt
